name: Run tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26"

      - name: Run Tests
        run: xcodebuild test -scheme HotwireNative -destination "name=iPhone 15 Pro" | xcpretty && exit ${PIPESTATUS[0]}
